remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Change Data Capture con Redis Data Integration
description: Redis Enterprise, una soluzione per il Change Data Capture
show_downloads: "true"
